version: '3'
services:
  discord:
    image: "rmwiesenberg/ode:latest"
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DICTIONARY_API_KEY=${DICTIONARY_API_KEY}
      - CATS_API_KEY=${CATS_API_KEY}